# Generated by Django 5.1.3 on 2024-12-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_localevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
