# Generated by Django 5.1.3 on 2024-12-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_localevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='localevent',
            name='type',
            field=models.CharField(choices=[('PARTY', 'Impreza'), ('MEETING', 'Spotkanie'), ('MUSIC', 'Muzyka'), ('OTHER', 'Inne')], default='OTHER', max_length=64),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='description',
            field=models.TextField(blank=True, default='Brak dodatkowych informacji o wydarzeniu.'),
        ),
    ]
