# Generated by Django 5.1.3 on 2024-12-14 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_helprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='date',
            new_name='expiration',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='type',
            field=models.CharField(choices=[('SHOPPING', 'Zakupy'), ('MEDICAL', 'Pomoc medyczna'), ('TRANSPORT', 'Transport'), ('CARE', 'Opieka'), ('WALK', 'Spacer'), ('OTHER', 'Inne')], default='OTHER', max_length=64),
        ),
    ]
